export const UserData = [
  {
    id: 1,
    profilePicture: "/images/profilePicture1.jpg",
    username: "Rahul",
  },
  {
    id: 2,
    profilePicture: "/images/profilePicture2.jpg",
    username: "Sita",
  },
  {
    id: 3,
    profilePicture: "/images/profilePicture3.jpg",
    username: "Vedasrith",
  },
  {
    id: 4,
    profilePicture: "/images/profilePicture4.jpg",
    username: "Malik",
  },
  {
    id: 5,
    profilePicture: "/images/profilePicture5.jpg",
    username: "Raghuvamshi",
  },
  {
    id: 6,
    profilePicture: "/images/profilePicture6.jpg",
    username: "sakshi",
  },
  {
    id: 7,
    profilePicture: "/images/profilePicture7.jpg",
    username: "Daniel",
  },
  {
    id: 8,
    profilePicture: "/images/profilePicture9.jpg",
    username: "Rakul",
  },
  {
    id: 9,
    profilePicture: "/images/profilePicture9.jpg",
    username: "Pradeep",
  },
  {
    id: 10,
    profilePicture: "/images/profilePicture10.jpg",
    username: "Gopichand",
  },
];

export const PostsData = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "/images/post1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "/images/post2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "/images/post3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "/images/post4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "/images/post5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "/images/post6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "/images/post7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "/images/post8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "/images/post9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "/images/post10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
